Added a new XSS app
globocom/secDevLabs pull request #437
Opened 2020-10-02 11:40 UTC by MEME-MAN234

App name - comment-killer

Comment and learn XSS!
(note: I did not use docker since this app uses react)

2020-10-05 19:45 UTC, Krlier requested changes
Hey, @MEME-MAN234! Thanks for taking the time to contribute to SecDevLabs. We greatly appreciate your contribution!

Up next we left some comments on what we believe you should improve before accepting this pull request. Please be sure to leave us any doubts you may have.

### Deploying the app
* It would be nice if you could add instructions on how to run this app using docker. We highly recommend that you use one of our [docker-compose.yml](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/deployments/docker-compose.yml) template.
* All of our projects use a Makefile, such as [this one](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/Makefile), in order to try and standardize all app start commands. We'd like you to add one for this app as well.

### App design
It would be great if you could enhance your app in a way that feels more like a real-life scenario/application with more depth to it. What do you think about extending your app to feature some other memes as well?

### App vulnerability
* We did not find any instructions in the [README.md](owasp-top10-2017-apps/a7/comment-killer/README.md) file on what steps/commands an attacker must do to exploit this application. Could you please better describe these steps? Try using one of our other [READMEs](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/README.md) as an example.
* We tried running this payload, but could not see the XSS working:
![image](https://user-images.githubusercontent.com/40367872/95124184-6d13cd80-0729-11eb-98d1-2e996f724e05.png)

2020-10-06 07:22 UTC, MEME-MAN234 commented
@Krlier Please review my PR request and tell me whether I should change something :)

2020-10-06 20:22 UTC, rafaveira3 requested changes
Hey, @MEME-MAN234! Thanks a lot for contributing to secDevLabs. Your app is looking cool and almost done! 🚀

We have added a few comments in your code. Could you take a look at them, please? Feel free to reach out to us if you need any kind of help! 🙃

2020-10-06 20:22 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/killer/Makefile
> +	chmod +x deployments/check-init.sh
To have this `msg` target work, you will have to have this `check-init.sh` as well. A good tip is to have a folder similar to [this one](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a7/gossip-world/deployments). Don't forget to edit `check-init.sh` to better fit the Comment-Killer app. 😄

2020-10-06 20:22 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/killer/docker-compose.yml
> +            - 3001:3000
Can you use the following code into this `docker-compose.yml`, please?

```yaml
version: "3.7"

services:
  app:
    container_name: app-a7 
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    ports:
      - "10007:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ".:/app"
      - "/app/node_modules"
    restart: always
```

You will need to fix your `deployments` folder! 😊

2020-10-06 20:22 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/killer/src/components/Blog.jsx
> +                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
Can you replace this `Lorem ipsum` text with a `Welcome to my Blog!` message?

2020-10-06 20:22 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/killer/src/components/Blog.jsx
> +            <div style={{ textAlign: "right", marginRight: 300 }}>
Can you replace this line of code to?

```html
<div style={{ textAlign: "center" }}>
```

2020-10-06 20:22 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/killer/src/components/Blog.jsx
> +                    src="https://i.kym-cdn.com/entries/icons/facebook/000/032/279/Screen_Shot_2019-12-30_at_11.26.24_AM.jpg"
Can you download this image and add it into this repository? We can reference it later on by doing something similar to:

```html
<img style={{ borderRadius: 1000, height: 100 }} src="images/logo.jpg"
```

2020-10-07 07:31 UTC, MEME-MAN234 commented
@rafaveira3 Thanks for the feedback! I have changed them :)

2020-10-07 18:59 UTC, Krlier requested changes
Hey, @MEME-MAN234! I'm really liking your contributions to secDevLabs!

We're almost done, I've just added some comments on your code. Please feel free to reach out to us if you need any kind of help! 🙂

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/deployments/Dockerfile
> +COPY package.json ./
Could you please update these commands with the new `Deployments` folder in mind?

When running `make install` and checking for container logs with `docker logs`, I'm receiving this error:
```sh
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +<img src="image/img1.png" alt="img1.png"/>
Could you please invert the order of the image and the `Comment-killer is a simple JS app that...` text to better fit our template? 🙂

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +
Before getting into `What is Cross-Site Scripting?`, could please add an Index here?

You can use [this one](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/README.md#index) as a template.

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +Then simply visit [http://localhost:3000/](http://localhost:3000/) ! 😆
Could you please change the app's port to `10007`, since we changed it in the `Docker-Compose` file?

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +
Would you mind using our template at the beginning of this section, as well? 

I'll post the content here, but it would be nice if you could also use the same markdown style as used in this [attack narrative](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/README.md#attack-narrative).
```markdown
Now that you know the purpose of this app, what could go wrong? The following section describes how an attacker could identify and eventually find sensitive information about the app or its users. We encourage you to follow these steps and try to reproduce them on your own to better understand the attack vector! 😜

Note: This attack narrative works best in Mozilla Firefox.

👀

Non-sanitization of user input allows for cross-site scripting

After inspecting the application, it is possible to identify that some entries are not sanitized and can be executed on a web browser. It occurs in search, comment, and post fields. The following images show this behavior when the following text is used as an input on these fields:
```

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +This website has interpreted your comment as a block of code, and stored it in it's server. Hence, whenever the comment section loads on anybody's machine, this block of code will be executed!
I couldn't load the same comment twice, every time I reloaded the page it changed. Is this what's expected to happen?

The app not storing the payload does not mean the XSS poses no threat, would you mind describing a bit how a local XSS could be bad? If you want, we could help you with that! 🙂

2020-10-07 18:59 UTC, Krlier commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +
It would also be interesting if you added an exploration phase of the Attack Narrative. We've done such before to demonstrate how an attacker could exploit the application once the vulnerability has been discovered.

As for some inspiration, you could have a look at [this section](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2017-apps/a7/gossip-world/README.md#-1) in one of our other XSS themed apps. If you want, we could give you a hand with that! 🙂

2020-10-07 20:58 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +<img src="image/img1.png" alt="img1.png"/>
![image](https://user-images.githubusercontent.com/8943477/95387201-c1a07f80-08c6-11eb-8c95-0e93e7ed57da.png)

2020-10-07 21:09 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +This website has interpreted your comment as a block of code, and stored it in it's server. Hence, whenever the comment section loads on anybody's machine, this block of code will be executed!
Great point, @Krlier. This vulnerability indeed is a Stored XSS although the app is not storing the comments in a database. 😅  

@MEME-MAN234, please tell us if you want to add a database into this app as well to store all the comments. We can help you with that! 

Another strategy here is to add a Reflected XSS scenario, in which an attacker can send the payload in a URL and the malicious code will be executed into the victim's browser.

2020-10-07 21:10 UTC, rafaveira3 commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +
Tell us if you need any help in this exploitation phase! We can send a commit to your branch! 🙃

2020-10-08 07:15 UTC, MEME-MAN234 commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +This website has interpreted your comment as a block of code, and stored it in it's server. Hence, whenever the comment section loads on anybody's machine, this block of code will be executed!
@Krlier and @rafaveira3 I would like some help in designing the database! Since this is a React app I would like the database to send and receive JSON

2020-10-08 07:18 UTC, MEME-MAN234 commented
I have changed the method of deployment, if that is not a problem(docker-compose). For development you can use `npm start` after navigating into the correct directory!

2020-10-08 07:23 UTC, MEME-MAN234 commented on owasp-top10-2017-apps/a7/comment-killer/README.md
> +This website has interpreted your comment as a block of code, and stored it in it's server. Hence, whenever the comment section loads on anybody's machine, this block of code will be executed!
I wanted to talk about this issue after the frontend(React) was done. Sorry, I did not address this issue soon enough!

2020-10-14 22:26 UTC, rafaveira3 commented
Hello, @MEME-MAN234! Thanks once again for contributing to secDevLabs. We will merge this PR as soon as you approve and merge [this other PR](https://github.com/MEME-MAN234/secDevLabs/pull/1).

2020-10-14 22:27 UTC, rafaveira3 approved these changes

2020-10-15 05:59 UTC, MEME-MAN234 commented
@rafaveira3 I have merged the PR request!

2020-10-15 15:10 UTC, merged