Owasp top10 2017 apps/a6/stegonography
globocom/secDevLabs pull request #473
Opened 2021-04-13 15:12 UTC by thiagolotufo

## This solution refers to which of the apps?

A/M# - owasp-top10-2017-apps/a6/stegonography

## What did you do to mitigate the vulnerability?

To mitigate this vulnerability, I changed the names of the session tokens. As this lab also had a session vulnerability, I have corrected it, although it is not the focus of the exercise.

## Did you test your changes? What commands did you run?

To correct the vulnerability, I changed the name of the tokens and created a user validation in the validation function of the JWT token.

- Changes in tokens names.

![Screen Shot 2021-04-13 at 12 07 23](https://user-images.githubusercontent.com/56851969/114575818-ed733800-9c50-11eb-8340-a7baf4c6e9a7.png)

- Validation of user in JWT Token validate function.

![Screen Shot 2021-04-13 at 12 06 12](https://user-images.githubusercontent.com/56851969/114576019-214e5d80-9c51-11eb-8113-d8e76d78ab83.png)

2021-04-20 18:23 UTC, gustavocovas requested changes
Hey, @thiagolotufo! Nice work changing the cookie name.

I left a comment regarding the verification of user names. Do we really need it?

Also, I can still exploit some security misconfigurations, such as:
- See error stack traces
- Sign in with default credentials

What can we do about these?

2021-04-20 18:23 UTC, gustavocovas commented on owasp-top10-2017-apps/a6/stegonography/app/index.js
> +        if (decoded.user != req.body.user.name) return res.status(500).send({ auth: false, message: 'Failed to authenticate token.' });
Why? Which routes have a `user.name` in the request body?

2021-04-20 19:40 UTC, thiagolotufo commented
Hi @gustavocovas,

I checked your changes and notice the changes.
Can you check if the vulnerabilities have been mitigated?

Thank you for your help!

2021-04-23 14:05 UTC, gustavocovas requested changes
Hey, @thiagolotufo!

I can still see error stack traces, such as when accessing http://localhost:10006/wrong:

```
Error: Failed to lookup view "error.html" in views directory "static/views"
    at Function.render (/app/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
    at /app/index.js:127:21
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/express/lib/router/index.js:635:15
    at next (/app/node_modules/express/lib/router/index.js:260:14)
```

Nodejs provides settings to help with that. Take a look at the [NODE_ENV](https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production) setting.

Also, the admin password is still hardcoded. What do you think about an environment variable? Of course, setting an environment variable implies that its value should be set somewhere. In the case of SecDevLabs, its OK if it is still hardcoded in some configuration file. But coding the application to read from an environment variable is a good exercise anyway 🙂

2021-04-27 16:33 UTC, gustavocovas commented
Cool! Now all vulnerabilities are mitigated, and the admin password can be set up configuring an environment variable. 🐼

2021-04-27 16:33 UTC, closed without merging