Fixing Makefile PROJECT names
globocom/secDevLabs pull request #598
Opened 2022-10-18 02:39 UTC by amintasvrp

## This solution refers to which of the apps?

All OWASP Top 10 (2021) apps.

## What changes were made ?

Changed the project name in the configuration files (MAKEFILE) of the OWASP Top 10 apps of 2021. In this sense, it consists of a contribution to solve the topic "Fix typo in deployments files(wrong owasp numeration)" of issue #561.

## Did you test your changes? What commands did you run?

The Make command was executed, before and after the changes, to ensure that the compilation behavior was maintained.

2022-10-18 12:44 UTC, fguisso requested changes

2022-10-18 12:44 UTC, fguisso commented on owasp-top10-2021-apps/a2/snake-pro/Makefile
> +INSECUREBIN ?= A2 SnakePro
Please, change for `snakeProA2`

2022-10-18 14:44 UTC, amintasvrp commented on owasp-top10-2021-apps/a2/snake-pro/Makefile
> +INSECUREBIN ?= A2 SnakePro
Changes done in 576c2bc.

2022-10-18 17:42 UTC, fguisso approved these changes

2022-10-18 17:42 UTC, fguisso commented
Awesome @amintasvrp thanks for your contribution.

2022-10-18 20:52 UTC, amintasvrp commented
Thank you, @fguisso !
Waiting for Globo Hacktoberfest approve.

![image](https://user-images.githubusercontent.com/25506431/196542275-5795d0b0-fc58-451e-8070-1ff650f1a635.png)

2022-10-26 00:07 UTC, amintasvrp commented
@fguisso, Globo Hacktoberfest website is not recognizing approved PR. Was there a problem?
![image](https://user-images.githubusercontent.com/25506431/197904243-ff8187fd-9a21-47ef-87a3-eeeb9db9a054.png)

2022-11-19 21:52 UTC, henriporto approved these changes
nice job! 👍

2022-11-19 21:54 UTC, merged